### ISSUE TITLE
Correct PDF file name

### ISSUE THREAD

**Issue by crstead** [emesterhazy/glossika-to-anki#14]
Hello - first off, excellent project and thank you for the effort and time spent to make this.

I've successfully split the audio, however the PDF splitting is having issues; I'm getting the following output:

```
Processing  GLOSSIKA-ENKR-EBK.pdf...unmatched
File name does not match
Skipping GLOSSIKA-ENKR-EBK.pdf
PDF extract complete!
```

What is the expected name format?

**Comment by crstead** [comment]
I had a look at the source code and figured out the file name format; actually the same solution as the previous issue. It should have been:

GLOSSIKA-ENKR-F1-EBK.pdf

I might contribute this to the readme, but at least the issue name will make it easy for others to find the solution.

**Comment by emesterhazy** [comment]
Hi @minceontoast - glad you figured it out. Please feel free to open a PR to update the readme. I think this is a great addition to make.

**Comment by emesterhazy** [comment]
On second thought, I'm also going to change the regex pattern [here](https://github.com/emesterhazy/glossika-to-anki/blob/e214c4d77b04d1d6173f8bfe8dab580704232802/glossika-to-anki/glossika_extract_pdf.py#L45) so that the string between the ENKR (the language id) and EBK is optional. I still think that the readme should discuss the expected file names, so feel free to open a PR :).
