### ISSUE TITLE
Error extracting sentences from Japanese PDFs

### ISSUE THREAD

**Issue by WannabeNihonjin** [emesterhazy/glossika-to-anki#2]
I really have no clue what I'm doing wrong, I've been working on this for 2+ hours. I have the mp3split folder in the python folder and when i use the glossika_split_audio all that happens is python pops up for half a second and then goes away.

Please help

**Comment by WannabeNihonjin** [comment]
I found someone who had used this before and he got the audio files to split no problem(still dont know what I did wrong)but now the genanki file doesnt do anything when I have both the split files and the txt doctuments in the output folder. Have no clue what to do.

**Comment by deepakjois** [comment]
So I am the person who has been helping @WannabeNihonjin 

The Glosssika PDFs throw an error during the extraction step. Here is a sample output on my setup:

```
$ python glossika_extract_pdf.py 

Processing 3 files...

Processing  GLOSSIKA-ENJA-F1-EBK.pdf...error
Something went wrong...found 0 sentences instead of 1,000
Processing  GLOSSIKA-ENJA-F2-EBK.pdf...error
Something went wrong...found 0 sentences instead of 1,000
Processing  GLOSSIKA-ENJA-F3-EBK.pdf...error
Something went wrong...found 0 sentences instead of 1,000
PDF extract complete!
```

It looks like it needs a similar fix to Cantonese that you made earlier.

**Comment by emesterhazy** [comment]
Thanks @deepakjois. The script identifies the beginning of each sentence by looking for a character or set or characters that indicate the  start of a phrase.

Based on the information you shared, I think the "日" character on [this line](https://github.com/emesterhazy/glossika-to-anki/blob/a847d30298919229978203b61c333ee87c67b896/glossika-to-anki/glossika_extract_pdf.py#L20)
should be changed to "JA".

`'JA': ['EN', '日', 'ROM']   # Japanese (before)` 
`'JA': ['EN', 'JA', 'ROM']   # Japanese (after)`

Can you test this change and let me know if it works? I'll investigate whether some versions of the PDFs use 日 instead of JA before pushing a fix to the repo.

**Comment by deepakjois** [comment]
I made that change in the script here, and it seems to work:

```
$ python glossika_extract_pdf.py 

Processing 3 files...

Processing  GLOSSIKA-ENJA-F1-EBK.pdf...complete
Processing  GLOSSIKA-ENJA-F2-EBK.pdf...complete
Processing  GLOSSIKA-ENJA-F3-EBK.pdf...complete
PDF extract complete!
```

@WannabeNihonjin please check your email for Anki deck.

**Comment by WannabeNihonjin** [comment]
Thank you both for all the help, the deck works perfectly.

**Comment by emesterhazy** [comment]
This is fixed now in the commit above.
